//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_pointage_tourniquet.BaseClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public Nullable<decimal> ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string NOM { get; set; }
        public string Type { get; set; }
    }
}
