//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_pointage_tourniquet.BaseClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LECTEUR> LECTEUR { get; set; }
        public virtual DbSet<MACHINE> MACHINE { get; set; }
        public virtual DbSet<PASSE> PASSE { get; set; }
        public virtual DbSet<PERSONNEL> PERSONNEL { get; set; }
        public virtual DbSet<POINTAGE> POINTAGE { get; set; }
        public virtual DbSet<SHIFT> SHIFT { get; set; }
        public virtual DbSet<SOCIETE> SOCIETE { get; set; }
        public virtual DbSet<ADMIN> ADMIN { get; set; }
    }
}
