//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_pointage_tourniquet.BaseClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONNEL()
        {
            this.POINTAGE = new HashSet<POINTAGE>();
            this.SHIFT1 = new HashSet<SHIFT>();
        }
    
        public string MAT { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string TEL { get; set; }
        public string ADR_P { get; set; }
        public string VILLE_P { get; set; }
        public string POSTE { get; set; }
        public Nullable<System.DateTime> DATE_EMB { get; set; }
        public Nullable<decimal> SALAIRE { get; set; }
        public Nullable<decimal> CODE_S { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<decimal> CODE { get; set; }
        public Nullable<decimal> IDEMPRIENT { get; set; }
    
        public virtual PASSE PASSE { get; set; }
        public virtual SHIFT SHIFT { get; set; }
        public virtual SOCIETE SOCIETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POINTAGE> POINTAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFT> SHIFT1 { get; set; }
    }
}
