//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_pointage_tourniquet.BaseClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIFT()
        {
            this.PERSONNEL = new HashSet<PERSONNEL>();
        }
    
        public decimal CODE { get; set; }
        public Nullable<decimal> CODE_S { get; set; }
        public string MAT { get; set; }
        public Nullable<System.DateTime> DATEDDEBUT { get; set; }
        public Nullable<System.DateTime> DATEDFIN { get; set; }
        public Nullable<System.DateTime> HEUREDEBUT { get; set; }
        public Nullable<System.DateTime> HEUREFIN { get; set; }
        public Nullable<System.DateTime> HEUREDEBUTPAUSE { get; set; }
        public Nullable<System.DateTime> HEUREFINPAUSE { get; set; }
        public Nullable<double> WEEKEND { get; set; }
        public Nullable<double> VACANCE { get; set; }
        public Nullable<double> JOURSFERIES { get; set; }
        public string LIBELLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONNEL> PERSONNEL { get; set; }
        public virtual PERSONNEL PERSONNEL1 { get; set; }
        public virtual SOCIETE SOCIETE { get; set; }
    }
}
