//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_pointage_tourniquet.BaseClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIETE()
        {
            this.MACHINE = new HashSet<MACHINE>();
            this.PERSONNEL = new HashSet<PERSONNEL>();
            this.SHIFT = new HashSet<SHIFT>();
        }
    
        public decimal CODE_S { get; set; }
        public string NOM_S { get; set; }
        public string ADR_S { get; set; }
        public string VILLE { get; set; }
        public Nullable<decimal> CODE_POSTAL { get; set; }
        public string TEL_S { get; set; }
        public string PAY { get; set; }
        public string FILIALE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MACHINE> MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONNEL> PERSONNEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFT> SHIFT { get; set; }
    }
}
